// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.10.0
// source: weixin.proto

package weixin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WeixinServiceClient is the client API for WeixinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeixinServiceClient interface {
	TicketRpc(ctx context.Context, in *TicketReq, opts ...grpc.CallOption) (*TicketRsp, error)
}

type weixinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeixinServiceClient(cc grpc.ClientConnInterface) WeixinServiceClient {
	return &weixinServiceClient{cc}
}

func (c *weixinServiceClient) TicketRpc(ctx context.Context, in *TicketReq, opts ...grpc.CallOption) (*TicketRsp, error) {
	out := new(TicketRsp)
	err := c.cc.Invoke(ctx, "/weixin.WeixinService/TicketRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeixinServiceServer is the server API for WeixinService service.
// All implementations must embed UnimplementedWeixinServiceServer
// for forward compatibility
type WeixinServiceServer interface {
	TicketRpc(context.Context, *TicketReq) (*TicketRsp, error)
	mustEmbedUnimplementedWeixinServiceServer()
}

// UnimplementedWeixinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWeixinServiceServer struct {
}

func (UnimplementedWeixinServiceServer) TicketRpc(context.Context, *TicketReq) (*TicketRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TicketRpc not implemented")
}
func (UnimplementedWeixinServiceServer) mustEmbedUnimplementedWeixinServiceServer() {}

// UnsafeWeixinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeixinServiceServer will
// result in compilation errors.
type UnsafeWeixinServiceServer interface {
	mustEmbedUnimplementedWeixinServiceServer()
}

func RegisterWeixinServiceServer(s grpc.ServiceRegistrar, srv WeixinServiceServer) {
	s.RegisterService(&WeixinService_ServiceDesc, srv)
}

func _WeixinService_TicketRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeixinServiceServer).TicketRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weixin.WeixinService/TicketRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeixinServiceServer).TicketRpc(ctx, req.(*TicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WeixinService_ServiceDesc is the grpc.ServiceDesc for WeixinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeixinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weixin.WeixinService",
	HandlerType: (*WeixinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TicketRpc",
			Handler:    _WeixinService_TicketRpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weixin.proto",
}
